# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmuxai < Formula
  desc "AI-Powered, Non-Intrusive Terminal Assistant"
  homepage "https://tmuxai.dev/"
  version "2.2.0"

  depends_on "tmux"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v2.2.0/tmuxai_Darwin_amd64.tar.gz"
      sha256 "51c726f036200fbefe2d78751b15770a8514199df6895fc18568e28afefe6385"

      define_method(:install) do
        bin.install "tmuxai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v2.2.0/tmuxai_Darwin_arm64.tar.gz"
      sha256 "e7072a09425954b6f87e7f31583b7930986b2af6c0417be1cca72e3df392ff32"

      define_method(:install) do
        bin.install "tmuxai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v2.2.0/tmuxai_Linux_amd64.tar.gz"
      sha256 "5cc89b0994861fdfa980aa15c50613ca5e7efaefe5d0aa2c7ee937b54c5d89fa"
      define_method(:install) do
        bin.install "tmuxai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v2.2.0/tmuxai_Linux_arm64.tar.gz"
      sha256 "1c6dbca9586d776c0b8d6367ce237dd19689c6cdd359ba527f610640c10df41e"
      define_method(:install) do
        bin.install "tmuxai"
      end
    end
  end

  test do
    system "tmuxai version"
  end
end
