# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tmuxai < Formula
  desc "AI-Powered, Non-Intrusive Terminal Assistant"
  homepage "https://tmuxai.dev/"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v1.0.0/tmuxai_Darwin_amd64.tar.gz"
      sha256 "4f09b067447b4bc353979bc51be552f4e15c011404670a23a0b3a9cbb506a2a8"

      def install
        bin.install "tmuxai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alvinunreal/tmuxai/releases/download/v1.0.0/tmuxai_Darwin_arm64.tar.gz"
      sha256 "f8f51b69fd1450e474f033e689c0744dcdef94f1fb761d45ee3111eb4a5bbd89"

      def install
        bin.install "tmuxai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alvinunreal/tmuxai/releases/download/v1.0.0/tmuxai_Linux_amd64.tar.gz"
        sha256 "36d69a39a5b08ed9708cf93c072238d55892ebc35257b385bf5473f42e6c5690"

        def install
          bin.install "tmuxai"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/alvinunreal/tmuxai/releases/download/v1.0.0/tmuxai_Linux_arm64.tar.gz"
        sha256 "dd8b20eefe1a868a8c6aaaded53c13c5983271113d8ce8e34cf8325868c7beb9"

        def install
          bin.install "tmuxai"
        end
      end
    end
  end

  test do
    system "tmuxai version"
  end
end
